- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  become: true

- name: Install packages
  apt:
    pkg: 
      - apt-transport-https
      - software-properties-common
      - vim
      - zsh
      - xclip
      - curl
      - htop
      - feh
      - maim
      - git
      - openssh-server
      - ca-certificates
      - curl
      - lsb-release
      - gnome-terminal
    state: latest
    update_cache: true
  become: true

- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu kinetic stable
    state: present
  become: true

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: true

- name: Add docker compose
  apt:
    name: docker-compose-plugin
    state: latest
    update_cache: true
  become: true

- name: Create the docker group
  group:
    name: docker
    state: present
  become: true

- name: Add the current user to the docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: true

- name: Enable the docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Enable the containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes
