- name: Install zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-autosuggestions"

- name: Install zsh-z plugin
  git: 
    repo: https://github.com/agkozak/zsh-z.git
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-z"

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-syntax-highlighting.git"

- name: Set zsh as default
  user:
    name: gabriel
    shell: /usr/bin/zsh
  become: true

